-- Bảng không có khóa ngoại
CREATE TABLE CHATLIEU (
    MACHATLIEU INT PRIMARY KEY IDENTITY(1,1),
    TENCHATLIEU NVARCHAR(50),
    GIANHAP MONEY,
    ANHCHATLIEU IMAGE
);

CREATE TABLE KHACHHANG (
    MAKHACH INT PRIMARY KEY IDENTITY(1,1),
    TENKHACH NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    SODIENTHOAI NVARCHAR(50) NOT NULL,
    GIOITINH NCHAR(10),
    LOAIKHACHHANG NVARCHAR(100),
    NGAYSINH DATETIME
);

CREATE TABLE NHANVIEN (
    MANHANVIEN INT PRIMARY KEY IDENTITY(1,1),
    TEN NVARCHAR(50) NOT NULL,
    GIOITINH NVARCHAR(10) NOT NULL,
    DIACHI NVARCHAR(50) NOT NULL,
    DIENTHOAI NVARCHAR(15) NOT NULL,
    NGAYSINH DATETIME NOT NULL,
    PASSWORD NVARCHAR(50),
    ISADMIN INT,
    EMAIL NVARCHAR(50),
    CHUCVU NCHAR(10),
    ANHNV IMAGE
);

CREATE TABLE THANHTOAN (
    MATHANHTOAN INT PRIMARY KEY IDENTITY(1,1),
    PHUONGTHUCTHANHTOAN NVARCHAR(50),
    GIAMGIA INT
);

-- Bảng có khóa ngoại
CREATE TABLE HANGHOANHAPKHO (
    MANHAPKHO INT PRIMARY KEY IDENTITY(1,1),
    MASANPHAM NCHAR(10) NOT NULL,
    TENSANPHAM NVARCHAR(200),
    SOLUONG INT,
    GIANHAP MONEY,
    GIABAN MONEY,
    MACHATLIEU INT,
    GHICHU NVARCHAR(1000),
    ANH IMAGE,
    CONSTRAINT PK_HANGHOANHAPKHO PRIMARY KEY (MANHAPKHO, MASANPHAM),
    CONSTRAINT FK_MACHATLIEU FOREIGN KEY (MACHATLIEU) REFERENCES CHATLIEU(MACHATLIEU)
);

CREATE TABLE HOADON (
    MAHD INT PRIMARY KEY IDENTITY(1,1),
    SOLUONG NCHAR(100),
    DONGIA MONEY,
    GIAMGIA NCHAR(1000),
    THANHTIEN MONEY,
    NGAYMUA DATETIME,
    TENSANPHAM NCHAR(1000),
    MASANPHAM NCHAR(10),
    CONSTRAINT FK_MASANPHAM FOREIGN KEY (MASANPHAM) REFERENCES HANGHOANHAPKHO(MASANPHAM)
);

CREATE TABLE LICHSUGIAODICH (
    MAGD INT PRIMARY KEY IDENTITY(1,1),
    MAKHACH NCHAR(10),
    SANPHAMDAMUA NVARCHAR(1000),
    SOLUONG NVARCHAR(1000),
    THANHTIEN MONEY,
    NGAYMUA DATETIME,
    PHUONGTHUCTHANHTOAN NVARCHAR(50),
    GIAMGIA NCHAR(1000),
    MANHANVIEN INT,
    CONSTRAINT FK_MAKHACH FOREIGN KEY (MAKHACH) REFERENCES KHACHHANG(MAKHACH),
    CONSTRAINT FK_MANHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
);

--Service Broker là một tính năng của SQL Server cho phép các ứng dụng nhận thông báo về thay đổi dữ liệu. 
--SqlDependency dựa vào Service Broker để hoạt động.
ALTER DATABASE QLBanHang SET ENABLE_BROKER